# Generated by Django 5.2.7 on 2025-11-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
                ('location', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=50)),
                ('Bath', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('ac', models.BooleanField(default=False)),
                ('parkign', models.BooleanField(default=False)),
                ('outdoor', models.BooleanField(default=False)),
                ('price_sqft', models.CharField(default='', max_length=150)),
                ('year_built', models.DateField(default='2022')),
                ('Listed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
